- name: SpotifyPro_FlaskPi
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/Harin329/SpotifyPro.git
      repository_path: /home/pi/Desktop/SpotifyPro

  tasks:
    - name: Install packages
      apt: 
        name:
          - git
          - python-pip
          - nginx
        update_cache: yes
        state: present

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'

    - name: Start Server
      community.general.gunicorn:
        app: 'spotify'
        chdir: '{{ repository_path }}'