- name: SpotifyPro_FlaskPi
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/Harin329/SpotifyPro.git
      repository_path: /home/pi/Desktop/SpotifyPro

  tasks:
    - name: Install packages
      apt: 
        name:
          - git
          - python-pip
          - nginx
        update_cache: yes
        state: present

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Create Virtual Env
      pip:
        requirements: '{{ repository_path }}/requirements.txt'
        virtualenv: '{{ repository_path }}/env'
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Copy .env configuration
      template: src=.env dest='{{ repository_path }}/.env'

    - name: Copy Systemd service configuration
      template: src=spotifypro.service.j2 dest=/etc/systemd/system/spotifypro.service
      notify:
        - restart systemd
    
    - name: Copy Systemd socket configuration
      template: src=spotifypro.socket.j2 dest=/etc/systemd/system/spotifypro.socket
      notify:
        - restart systemd

    - name: Make sure our server is running
      systemd: name=spotifypro daemon_reload=true state=started

    - name: Copy Nginx site
      template: src=spotifypro.nginx.j2 dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx
        - restart systemd

    - name: Make sure nginx is running
      service: name=nginx state=started

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart systemd
      service: name=spotifypro daemon_reload=true state=restarted scope=global