- name: SpotifyPro_FlaskPi
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/Harin329/SpotifyPro.git
      repository_path: /home/pi/Desktop/SpotifyPro

  tasks:
    - name: Install packages
      apt: 
        name:
          - git
          - python-pip
          - nginx
        update_cache: yes
        state: present

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'

    - name: Copy Systemd service configuration
      template: src=spotifypro.service.j2 dest=/etc/systemd/system/spotifypro.service
    
    - name: Copy Systemd socket configuration
      template: src=spotifypro.socket.j2 dest=/etc/systemd/system/spotifypro.socket

    - name: Make sure our server is running
      service: name=spotifypro state=started

    - name: Copy Nginx site
      template: src=spotifypro.nginx.j2 dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service: name=nginx state=started

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted